version: '2'

services:
  sftp:
    image: atmoz/sftp
    container_name: SFTP-Server
    volumes:
      - ./host/users.conf:/etc/sftp/users.conf:ro
      - ./conf:/etc/ssh/ 
      - ./conf/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key 
      - ./conf/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    ports:
      - "22:22"
    #command: foo:pass:1001