version: '2'

services:
  portainer:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "6080:80"
    command: -H unix:///var/run/docker.sock
    volumes:
      - ./../dck_volumes/Ubuntu_dsk:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
