version: "3"
services:
    jobscheduler:
        image: miraiworks/jobscheduler:latest
        links:
          - mysql
        volumes:
          - ./live:/opt/jobscheduler/data/scheduler/config/live
        ports:
          - "4446:4446"
          - "40444:40444"
      
    mysql:
        image: mariadb:latest
        environment:
          MYSQL_USER: jobscheduler
          MYSQL_PASSWORD: jobscheduler
          MYSQL_ROOT_PASSWORD: scheduler
          MYSQL_DATABASE: jobscheduler