version: '2'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./../dck_volumes/postgresql:/var/lib/postgresql/data

  odoo13:
    image: odoo:13
    depends_on:
      - db
    ports:
      - "10013:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./odoo_data/addons:/mnt/extra-addons
      - ./odoo_data/etc:/etc/odoo
    restart: always    