version: '3.5'

services:
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --sql_mode=""
    container_name: MySQL-8.0.21
    restart: always
    environment:
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbuser'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql/
