version: '3'
services:
  postgres_db:
    image: postgres
    container_name: Postgrest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=freegame_DB
      - PGDATA=/tmp
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data